### ISSUE TITLE
Region dump cache?

### ISSUE THREAD

**Issue by Time6628** [Shevchik/AutoSaveWorld#10]
Whenever the server saves it spews this error:
http://hastebin.com/huyomikiyu.vbs
Any ideas?

**Comment by Shevchik** [comment]
What's your server version?

**Comment by Time6628** [comment]
@Shevchik 1.7.10

**Comment by Shevchik** [comment]
1.7.10 what? Spigot, Caludron, CraftBukkit, Something else?

**Comment by Time6628** [comment]
1.7.10 Cauldron

**Comment by Shevchik** [comment]
Use latest dev build.
