### ISSUE TITLE
Auto Restart time issue?

### ISSUE THREAD

**Issue by Leymooo** [Shevchik/AutoSaveWorld#12]
I have
autorestart:
  enabled: true
  broadcast: true
  scriptpath: ''
  time:
- 05:00
- 12:00
- 20:00
  countdown:
    enabled: true
    broadcastonsecond:

```
- 15
- 10
- 9
- 8
- 7
- 6
- 5
- 4
- 3
- 2
- 1
```

  commands: []
  juststop: true

plugin change it to 
  time:
- 05:00
- 720
- 1200

**Comment by Shevchik** [comment]
Read how YAML works first. And how to use it properly.
