### ISSUE TITLE
Broadcasts to 2 lines

### ISSUE THREAD

**Issue by Mickroz** [Shevchik/AutoSaveWorld#16]
Hi im using this for the autosave and restart function, but it's broadcasting to 2 lines instead of 1.
result

```
[12:58:23 INFO]: [Broadcast]
[12:58:24 INFO]: AutoSave Complete
```

expecting

```
[12:58:23 INFO]: [Broadcast] AutoSave Complete
```

config

```
broadcast:
  pre: '&d[Broadcast]&7'
  post: '&9AutoSave Complete'
```

**Comment by Shevchik** [comment]
broadcast:
  pre: '&d[Broadcast]&7 &9AutoSave Started'
  post: '&d[Broadcast]&7 &9AutoSave Complete'

Pre and post are not parts of the message, they are messages before and after the save.

**Comment by Mickroz** [comment]
Ahh tnx for clarifying!
