### ISSUE TITLE
1.9 errors

### ISSUE THREAD

**Issue by ChanceSD** [Shevchik/AutoSaveWorld#19]
Getting that every time it tries to save, i believe.

http://pastebin.com/Fc9jtkbY

**Comment by Shevchik** [comment]
Disable structure saving disabler for now.

**Comment by ChanceSD** [comment]
It's already disabled, unless you mean in spigot.yml

**Comment by Shevchik** [comment]
WARN failed to workaround stucture saving, saving world using normal methods.
That clearly says that you have disablestructuresaving set to true in config.

**Comment by ChanceSD** [comment]
You said to disable structure saving... i will put it on false then.

**Comment by Shevchik** [comment]
I said disable structure saving disabler. Double no, you see?
