### ISSUE TITLE
No backup if server restarts before

### ISSUE THREAD

**Issue by Mastergalen** [Shevchik/AutoSaveWorld#2]
I have rtoolkit installed, which restarts the server every 5 hours.

I then have ASW set to back the map up every 24 hours.

It seems that when the server restarts, the counter is reset back to 0 hours, so that a backup never runs.

**Comment by Shevchik** [comment]
I know that, you can use AutoConsoleCommand to schedule backup at fixed time.

Maybe i will fix that, but that is a low priority bug.

**Comment by Mastergalen** [comment]
Ah, nice tip, thanks.
