### ISSUE TITLE
Плагин портит свои конфиги при рестарте или релоаде

### ISSUE THREAD

**Issue by Krysinski** [Shevchik/AutoSaveWorld#22]
Плагин портит свои конфиги при рестарте или релоаде. Пробовал разные версии:
1. 4.14.2
2.  build 882
вот результат в config.yml после перезагрузки сервера:
time:
    - 01:05
    - 07:05
    - 785
    - 1145
В итоге перезагрузка не наступает в запланированное время. Блокировка записи на файле не помогает.

**Comment by Shevchik** [comment]
Потому что надо внимательней смотреть на примеры, авось в следующий раз кавычки не забудешь.

**Comment by Krysinski** [comment]
кавычки пропадают почему-то

**Comment by Shevchik** [comment]
Кавычки пропадают только там где они не нужны, а где нужны - остаются.
