### ISSUE TITLE
Error on renegeration

### ISSUE THREAD

**Issue by Faicu** [Shevchik/AutoSaveWorld#24]
I belive is a error with preciousstones. I have latest preciousstones from dev and latest autosaveworld from dev.
Log: http://pastebin.com/dnaNsGTL

**Comment by Faicu** [comment]
Stil unsolved, will you solve it?

**Comment by Shevchik** [comment]
preciousstones changed packages and classes. I will fix this in next version.

**Comment by Faicu** [comment]
You stil didn't fixed...

**Comment by Shevchik** [comment]
AutoSaveWorld development is temprorarily on hold

**Comment by Faicu** [comment]
Any ETA about resume?
