### ISSUE TITLE
SFTP error on backup

### ISSUE THREAD

**Issue by ChanceSD** [Shevchik/AutoSaveWorld#26]
So the first backup i made worked fine. It uploaded the files correctly but now i get this error every time.

http://pastebin.com/fH570Dpt

Any ideas?

**Comment by Shevchik** [comment]
No idea, look in your sftp server log, if it has one.
Server thrown generic error on directory create.

**Comment by ChanceSD** [comment]
In sftp log i got this

sftp-server[691]: mkdir name "/asw/" mode 0777
sftp-server[691]: sent status Failure

So maybe the error is because the directory already exists?

**Comment by Shevchik** [comment]
It shoudn't send a failure in such case. Try another sftp server software.

**Comment by ChanceSD** [comment]
Do you have any suggestion? I was just using default from centos, installed vsftp but same result.

**Comment by Shevchik** [comment]
No idea, i used windows sftp server software when testing.
Will try to workaround that somehow.

**Comment by ChanceSD** [comment]
If you could just check if the main directory exists before executing the mkdir it would probably work, i didn't look at the code so just guessing. In my case they are the default i believe /asw and /asw/backups
Because the first backup always works perfectly when those directories don't exist yet.

**Comment by Shevchik** [comment]
Yea, that's what i will do when i have time.
