### ISSUE TITLE
Ошибка при purge

### ISSUE THREAD

**Issue by falget** [Shevchik/AutoSaveWorld#27]
Здвраствуйте, при попытке сделать /asw purge сервер подвисает немного после чего уходит в автоматический рестарт, в итоге происходит реген приватов неактивных игроков и все, все остальные данные остаются, а в логах перед рестартом пишет вот это: http://pastebin.com/FG4n4fPH
Spigot 1.10.2, WE 6.1.3, WG 6.1.3, EssentialsX v2.0.1-b370.
Purge настроен на удаление привата и реген территории, essentials и .dat файл.

**Comment by Shevchik** [comment]
Потому что мозги надо иметь. Как думаете сколько времени занимает реген регионов, и что надо сделать перед тем как включать его?, правильно, отключить любые рестартеры по таймауту.
