### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by Faicu** [Shevchik/AutoSaveWorld#34]
Can you give me details about this new feature that you implemented?
http://image.prntscr.com/image/0e719d5ac8274bd98e6ab62ffafac3af.png
It's is very useful and I want to use it but I don't know from where to get:
    authfilepath: ''
    rootfolderid: ''
Thanks!

**Comment by Shevchik** [comment]
Yeah, i will make a video about it when i have time.

**Comment by Faicu** [comment]
Explain me a little bit, if you want, I can make a video for you too :)

**Comment by Shevchik** [comment]
See this. It's crappy because my micro sucks, but at least it's a full tutorial.
https://www.youtube.com/watch?v=JPkzcL-NJ5E

**Comment by Faicu** [comment]
Thanks for this man!
