### ISSUE TITLE
Не реботает worldregen на thermos с 4.15

### ISSUE THREAD

**Issue by kourpo** [Shevchik/AutoSaveWorld#37]
Перестала работать функция после обновы 
ввожу /asw regenworld DIM-34 world, сервер перезапускается но карта остается без изменений

[AutoSaveWorld WorldRegenCopyThread/INFO] [autosaveworld.core.AutoSaveWorld/]: [AutoSaveWorld] WorldRegenThread Started
[AutoSaveWorld WorldRegenCopyThread/INFO] [autosaveworld.core.AutoSaveWorld/]: [AutoSaveWorld] WG found, adding to copy list
[AutoSaveWorld WorldRegenCopyThread/INFO] [autosaveworld.core.AutoSaveWorld/]: [AutoSaveWorld] Stopping server and adding shutdown hook to perform needed actions
[Server thread/INFO] [FML/]: Unloading dimension -34
[AutoSaveWorld AutoRestartThread/INFO] [/]: Server is restarting
[AutoSaveWorld AutoRestartThread/INFO] [autosaveworld.core.AutoSaveWorld/]: [AutoSaveWorld] AutoRestarting server

**Comment by Shevchik** [comment]
Папка регионов для мира указана неверно.
