### ISSUE TITLE
files and .jar

### ISSUE THREAD

**Issue by Escanor2019** [Shevchik/AutoSaveWorld#66]
why you don't have the option to backup files and .jar? or all folder ./*?
start.bat
start.sh
server.jar
server.properties
bukkit.yml
spigot.yml
config.yml
bungee.yml

**Comment by Escanor2019** [comment]
![image](https://user-images.githubusercontent.com/47899748/74284366-520bcd80-4d02-11ea-9e67-2da6460f81fb.png)
what is
localfs
otherfolders
and excludefolders
?
i can use /%serverdir%/server.properties?

**Comment by Shevchik** [comment]
Otherfolders is a list of other folders and files you wish to backup.
You can use absolete paths, or paths relative to the server root folder.

**Comment by Escanor2019** [comment]
what i want to know is how to specify the relative folder of the server
./server.jar
/server.jar
$serverfolder/server.jar
or pluginfolder or destinationfolder back dir: ../../../server.jar

**Comment by Escanor2019** [comment]
is {server folder} like in Performs a world backups({server folder}/backups/)?

**Comment by Escanor2019** [comment]
![image](https://user-images.githubusercontent.com/47899748/74285247-386b8580-4d04-11ea-9900-927897f35a09.png)
