### ISSUE TITLE
Relative Directory

### ISSUE THREAD

**Issue by Escanor2019** [Shevchik/AutoSaveWorld#67]
look https://github.com/Shevchik/AutoSaveWorld/issues/66

what i want to know is how to specify the relative folder of the server
./server.jar
/server.jar
$serverfolder/server.jar
or pluginfolder or destinationfolder back dir: ../../../server.jar

is {server folder} like in Performs a world backups({server folder}/backups/)?

look
![image](https://user-images.githubusercontent.com/47899748/74289234-3ce86c00-4d0d-11ea-962b-65c8179f9855.png)

**Comment by Escanor2019** [comment]
for
start.bat
start.sh
server.jar
server.properties
bukkit.yml
spigot.yml
config.yml
bungee.yml

**Comment by Shevchik** [comment]
Literally them, because they are in the server folder root.

```
- server.jar
- bukkit.yml
- spigot.yml
- config.yml
```
