### ISSUE TITLE
Backup every file in main directory

### ISSUE THREAD

**Issue by RudyB** [Shevchik/AutoSaveWorld#7]
I love your plugin and I love how I can configure it to backup my plugins and all of my world but is there a way to configure it to backup all the files in my server directory?

**Comment by Shevchik** [comment]
Add your server folder to otherfolders. Don't forget to move your backup directory out of server directory before that.

**Comment by RudyB** [comment]
what about all the loose files that aren’t in folders?

**Comment by Shevchik** [comment]
I said to add the server folder, not the folders in the server folder
