### ISSUE TITLE
It does not save the world

### ISSUE THREAD

**Issue by ghost** [Shevchik/AutoSaveWorld#8]
http://pastebin.com/Hi7mdCgw

KCauldron-1.7.10-1420.104-server.jar
ASW #849

**Comment by Shevchik** [comment]
Damn, i need a better server detection code than by just the server brand.

It still saves the map actually, because in case of failing to do no structure save it will just fallback to normal one. But the saveLevel error loooks intersting, it should be in craftbukkit.

**Comment by Shevchik** [comment]
Should be fixed

**Comment by ghost** [comment]
no :(

**Comment by Shevchik** [comment]
Try now

**Comment by ghost** [comment]
good, now there is no error. But now I'm not sure whether the world is saved :)

**Comment by Shevchik** [comment]
It was anyway, there is a fallback save mode in case shit like that happens.
